# Generated by Django 4.0.5 on 2022-06-28 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=225)),
                ('barrio', models.CharField(max_length=225)),
                ('no_avenida', models.IntegerField()),
                ('no_calle', models.IntegerField()),
                ('pais', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=225)),
                ('apellido', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('domicilio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.domicilio')),
            ],
        ),
    ]
